// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVUYW0n4xDG_ZI9bgr-GHTeixah6Neb3s',
    appId: '1:939889013764:web:2d77a16e07d392a6c77151',
    messagingSenderId: '939889013764',
    projectId: 'deliveryapp-3b8a8',
    authDomain: 'deliveryapp-3b8a8.firebaseapp.com',
    databaseURL: 'https://deliveryapp-3b8a8-default-rtdb.firebaseio.com',
    storageBucket: 'deliveryapp-3b8a8.appspot.com',
    measurementId: 'G-8K4WVQCDJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdKNZV8iugW8GHBRp0qm66w8RZyUKfdfI',
    appId: '1:939889013764:android:332f21834f803aa7c77151',
    messagingSenderId: '939889013764',
    projectId: 'deliveryapp-3b8a8',
    databaseURL: 'https://deliveryapp-3b8a8-default-rtdb.firebaseio.com',
    storageBucket: 'deliveryapp-3b8a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdvrDkE8G3np1HENLyEaIJ6N5eHklH_Wg',
    appId: '1:939889013764:ios:ad4c5fe041f3c065c77151',
    messagingSenderId: '939889013764',
    projectId: 'deliveryapp-3b8a8',
    databaseURL: 'https://deliveryapp-3b8a8-default-rtdb.firebaseio.com',
    storageBucket: 'deliveryapp-3b8a8.appspot.com',
    iosClientId: '939889013764-e4nnh545pcjpkntd5impuks7hiqi9upo.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryAppFominhas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdvrDkE8G3np1HENLyEaIJ6N5eHklH_Wg',
    appId: '1:939889013764:ios:303c5431da324492c77151',
    messagingSenderId: '939889013764',
    projectId: 'deliveryapp-3b8a8',
    databaseURL: 'https://deliveryapp-3b8a8-default-rtdb.firebaseio.com',
    storageBucket: 'deliveryapp-3b8a8.appspot.com',
    iosClientId: '939889013764-ni9lp5gidm940tgi2k4lv0n9iq79n888.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryAppFominhas.RunnerTests',
  );
}
